### Test Payment Request to nginx (via exposed port in host)
POST http://localhost:9999/payments
Content-Type: application/json

{
  "amount": 19.90,
  "correlation_id": "{{$guid}}"
}

### Test Payment Request (direclt to payment processor debug only)
POST http://localhost:8001/payments
Content-Type: application/json

{
  "requestedAt":"2025-08-05T22:28:30Z",
  "amount": 19.90,
  "correlationId": "{{$guid}}"
}

### Test Summary
GET http://localhost:9999/payments-summary

### Test Summary
GET http://localhost:9999/api1/payments-summary?localOnly=true

### Test Summary
GET http://localhost:9999/api2/payments-summary?localOnly=true
